pipeline {
    agent { node { label 'AGENT' } }

    stages {
        stage('Terraform init') {
            steps {
                sh ''' 
                    ls -l
                    cd session-01
                    pwd
                '''
            }
        }
        stage('Test') {
            steps {
                sh ''' 
                    ls -l
                    cd session-01
                    pwd
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh ''' 
                    ls -l
                    cd session-01 
                    pwd
                '''
            }
        }
    }

    post{
        success{
            echo 'Successfull'
        }
        failure{
            echo 'Failed'
        }
        always{
            echo 'Hello Always'
        }
    }
}