pipeline {
    agent { node { label 'AGENT' } }
    // options {
    //     ansiColor('xterm')
    // }
    stages {
        stage('Terraform init') {
            steps {
                sh ''' 
                    ls -l
                    cd session-01
                    pwd
                    terraform init
                '''
            }
        }
        stage('Terraform plan') {
            steps {
                sh ''' 
                    ls -l
                    cd session-01
                    pwd
                    terraform plan
                '''
            }
        }
        stage('Terraform apply') {
            steps {
                sh '''
                    cd session-01 
                    pwd
                '''
            }
        }
    }

    post{
        success{
            echo 'Successfull'
        }
        failure{
            echo 'Failed'
        }
        always{
            echo 'Hello Always'
        }
    }
}